### ISSUE TITLE
 _RELEASE flag is set to false ?

### ISSUE THREAD

**Issue by VincentDauliacKPC** [cedricvlt/streamlit-condition-tree#13]
I tried to install this component but get the error : 

`Your app is having trouble loading the streamlit_condition_tree.streamlit_condition_tree component. The app is attempting to load the component from http://localhost:3001, and hasn't received its Streamlit.setComponentReady() message.`

I think this is due to the _RELEASE flag in the __init__.py file that should be set to True.

for reference :
https://discuss.streamlit.io/t/issues-with-custom-component-in-deployed-app/73035 
https://docs.streamlit.io/develop/concepts/custom-components/publish

**Comment by anovember** [comment]
~I'm getting the same error - how was this issue resolved?~

It looks like snowflake anaconda channel doesn't properly build the package - after installing, `__init__.py` has `_RELEASE=False` and the `frontend/build` directory doesn't exist.  https://repo.anaconda.com/pkgs/snowflake/
